### PR TITLE
[WINDUPRULE-757] microprofile_removed_from_eap ruleset

### PR DESCRIPTION
**Pull request by emmartins**
Issue: https://issues.redhat.com/browse/WINDUPRULE-757

### CODE REVIEW

**Comment by emmartins** [comment]
Please note that the links are invalid, due to related content in EAP 7.4 Migration Guide not yet available, even as staged

**Comment by PhilipCattanach** [comment]
@emmartins - I have reviewed the code and tested this rules set. Everything looks fine.  Thank you!
The links didn't work but I presume this is because the guide hasn't been published yet.
Marco is working on a fix https://github.com/windup/windup/pull/1417 for some Eclipse dependencies issues that should be merged to master shortly and will allow the default tests above to complete. When those things are done I'll merge this to master.

**Comment by emmartins** [comment]
@PhilipCattanach yes, in this case there is no docs content related with this yet, I will let you know when that is solved

**Comment by mrizzi** [comment]
retest

**Comment by emmartins** [comment]
@PhilipCattanach @mrizzi updated the links with the expected final URLs

**Comment by PhilipCattanach** [comment]
Tested the rules successfully and verified the documentation using the latest preview https://jenkins.dxp.redhat.com/job/CCS/job/ccs-mr-preview/2442/artifact/docs/migration-guide/preview/index.html#migration-review-deprecated_and_unsupported_features

**Pull request merged**
