### PR TITLE
Add new runtime springboot and add JPA as supported

### PR DESCRIPTION
**Pull request by showpune**
1)  Add springboot as new runtime label
1) EJB/JNDI/JTA... related stuff can't run on springboot
2) JPA can be load by springboot
3) JAX,CDI can be load by springboot by 3rd starter
4) Distinguish the spring web start with standalone jar and war in tomcat
@agoncal , please also check

### CODE REVIEW

**Comment by showpune** [comment]
@mrizzi , you help to check this?

**Comment by mrizzi** [comment]
@showpune hi!
This week the Windup team has been busy in working on the next 6.2 release with many bug fixes.
Next week I hope we'll (try to) reserve some time to look into your PR.

**Comment by PhilipCattanach** [comment]
Here is a list of the Spring related tags that are not referenced in the springboot label within embedded.windup.label.xml 
Spring, Spring Batch, Spring Boot, Spring Boot Actuator, Spring Boot Flo, Spring Cloud Function, Spring Data,  Spring Data JPA, Spring DI, Spring Integration, Spring JMX, Spring Messaging Client, Spring MVC, Spring Scheduled, Spring Security, Spring Test, Spring XML

**Comment by showpune** [comment]
@PhilipCattanach , related spring technology usage are added

**Comment by PhilipCattanach** [comment]
@showpune - Thanks you. I'll test the PR now.

**Comment by mrizzi** [comment]
@showpune @PhilipCattanach I've shared some potential enhancements to this PR in https://github.com/showpune/windup-rulesets/pull/1 where I provided also the context behind the changes.

Please take a look and let me know what you think about them and in case please merge that PR.

**Comment by showpune** [comment]
@mrizzi , it is OK to me and merged

**Comment by PhilipCattanach** [comment]
Reviewed and tested successfully.
Thank you @showpune and @mrizzi

**Comment by PhilipCattanach** [comment]
PR linked to JIra https://issues.redhat.com/browse/WINDUPRULE-1001

**Pull request merged**
