### PR TITLE
JBEAP-2704: Update JBoss EAP 6 documentation links to point to the latest 6.4 version

### PR DESCRIPTION
**Pull request by sgilda**
@bergerhoffer : Would you mind doing a review of these updated links to our docs?

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by jsight** [comment]
@windupgithubbot1 test this please

**Comment by bergerhoffer** [comment]
@sgilda @jsight These updated links look good to me and I don't see any other instances of older EAP 6 doc links. Thanks @sgilda!

**Comment by jsight** [comment]
Merged, thanks!

**Comment by sgilda** [comment]
Thanks @bergerhoffer and @jsight !

**Pull request merged**
