### PR TITLE
WINDUPRULE-624: springboot cloud data flow to quarkus rule

### PR DESCRIPTION
**Pull request by m-brophy**
https://issues.redhat.com/browse/WINDUPRULE-624

### CODE REVIEW

**Comment by PhilipCattanach** [comment]
@m-brophy Hi Mark, the rules look fine and my tests ran successfully. The automated tests appear to be failing though. Can you look into that? Thanks.

**Comment by m-brophy** [comment]
@PhilipCattanach the automated tests are failing because of links being unavailable in pre-existing tests, so i think everything is fine with this PR

**Comment by mrizzi** [comment]
retest

**Review by jonathanvila — APPROVED** [review]
LGTM :+1

**Pull request merged**
