### PR TITLE
[WINDUPRULE-785] PropertyChangeListeners removed

### PR DESCRIPTION
**Pull request by jmle**
See [WINDUPRULE-785](https://issues.redhat.com/browse/WINDUPRULE-785).

### CODE REVIEW

**Comment by PhilipCattanach** [comment]
@jmle I have looked at the code and it appears to be fine. There is a conflict with another PR that I have just merged to master today. Could you update the PR and renumber your rules in this PR to resolve the conflict please.

**Comment by jmle** [comment]
@PhilipCattanach it should be fine now

**Comment by PhilipCattanach** [comment]
@jmle I see Andrew Hughes hasn't responded to your request for more information about how to deal with issues of this type.
I will add a comment to Jira to chase him up. And I should be meeting with him in person this afternoon, so I'll mention it on the call too. 
Regarding the message wording I think it is important to have all of the text from the Jira, so add  _", which are the methods that previously triggered property change events for the registered listeners."_ 
Also have a link 
APIs removed JDK 9 
with a url of https://docs.oracle.com/en/java/javase/16/migrate/removed-apis.html#GUID-B96BD00F-12A4-493A-9907-2FFE8DA6748C

**Comment by PhilipCattanach** [comment]
@jmle - I have just reran the rules. The message for the removePropertyChangeListener() is longer and more informative than the addPropertyChangeListener(). I think it would be better for both rules to have the message text 
", which previously triggered property change events for the registered listeners." 
And both rules should have the **APIs removed in JDK 9** link.

Note the space between JDK and 9. 
I don't mean to be picky, but the title should match the title of the section of the document the user is taken to.

**Comment by jmle** [comment]
@PhilipCattanach sorry for that, I think I mistakenly updated only one of the two rules.

**Comment by PhilipCattanach** [comment]
Thanks @jmle - I have just resolved some conflicts and retested. The retest was successful, everything looks good.
As soon as the automated checks complete I will merge it to master.

**Pull request merged**
