### PR TITLE
[WINDUPRULE-432,433,435,436,437,438] - camel components moved out of camel-core

### PR DESCRIPTION
**Pull request by mmelko**
https://issues.redhat.com/browse/WINDUPRULE-432 - `camel-zip-deflater` 
https://issues.redhat.com/browse/WINDUPRULE-433  `camel-attachements` 
https://issues.redhat.com/browse/WINDUPRULE-435  `camel-dataformat` 
https://issues.redhat.com/browse/WINDUPRULE-436  `camel-language` 
https://issues.redhat.com/browse/WINDUPRULE-437  `camel-rest` 
https://issues.redhat.com/browse/WINDUPRULE-438 `camel-xpath`

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by mrizzi** [comment]
test this please

**Comment by mmelko** [comment]
retest

**Comment by mrizzi** [comment]
add to whitelist

**Comment by mmelko** [comment]
Please remove label "Depend on another PR". PR is already merged to master.

**Comment by mmelko** [comment]
@m-brophy thanks for the review. All changes should be included now.

**Pull request merged**
