### PR TITLE
add azure-jni-native-code rule

### PR DESCRIPTION
**Pull request by KaiqianYang**

### CODE REVIEW

**Comment by PhilipCattanach** [comment]
Hi @KaiqianYang 
This ruleset is just a copy of jni-native-code.windup.xml that was originally under the openshift directory, but that directory has now been renamed cloud-readiness. There are some Red Hat links in that ruleset - jni-native-code.windup.xml. Are you still of the opinion that you would like this ruleset added?

**Comment by agoncal** [comment]
@KaiqianYang if it's an existing rule, you should override the rule (see https://github.com/Azure/windup-rulesets/issues/23). But let me know if you manage to make it work, because so far I haven't succeeded in overidding a rule

**Comment by KaiqianYang** [comment]
@agoncal So <overrides> only works when the target technologies of the original rule and the overriding rule has overlaps, like my this PR https://github.com/windup/windup-rulesets/pull/940, it worked because azure target is the subset of targets of technology usage.

**Comment by agoncal** [comment]
@KaiqianYang I am trying something different. Bare with me and @mrizzi. Looks like we nearly found a way to do overriding:

https://github.com/Azure/windup-rulesets/pull/47

**Comment by KaiqianYang** [comment]
> 



> @KaiqianYang I am trying something different. Bare with me and @mrizzi. Looks like we nearly found a way to do overriding:
> 
> [Azure/windup-rulesets#47](https://github.com/Azure/windup-rulesets/pull/47)

@agoncal Great! Glad to hear this.

**Comment by agoncal** [comment]
@KaiqianYang now that https://github.com/Azure/windup-rulesets/pull/90 has been merged, is this PR still relevant ? Or should it just be closed without being merged ?

**Comment by KaiqianYang** [comment]
> @KaiqianYang now that https://github.com/Azure/windup-rulesets/pull/90 has been merged, is this PR still relevant ? Or should it just be closed without being merged ?

Closed this one

**Pull request closed without merging**
