### PR TITLE
WINDUPRULE-670: spring aop source analysis rule

### PR DESCRIPTION
**Pull request by m-brophy**
https://issues.redhat.com/browse/WINDUPRULE-670

### CODE REVIEW

**Comment by PhilipCattanach** [comment]
@m-brophy the <project> rules are firing fine but the <dependency> one isn't.
The reason is that the hidden file that we use for providing the SHA1 hashes 
windup-rulesets/rules-reviewed/quarkus/springboot/tests/.mta/cache/nexus-indexer-data/test.archive-metadata.txt
does not contain the SHA1 hash for the spring-aop artifact.

Can you add this line to the bottom of the file
ad6d33979070888c8c062faaa178f63ed49b12c2 org.springframework:spring-aop:4.3.15.RELEASE

Then change the test to expect 3 rather than 2 issues. Then it should be good.  
Thanks,
Phil

**Comment by PhilipCattanach** [comment]
@m-brophy - retested successfully. Thanks!

**Review by mrizzi — COMMENTED** [review]
`spring-boot-starter-aop` project-artifact condition is still missing and must be added in this PR to fully cover https://issues.redhat.com/browse/WINDUPRULE-670's requirements.

**Comment by PhilipCattanach** [comment]
@m-brophy Thanks Mark I can see the spring-boot-starter-aop artifact in the PM triggering the rule.
@mrizzi - As the change has been applied and successfully tested are you OK for me to merge this PR? Thanks

**Review by mrizzi — APPROVED** [review]
Great @m-brophy, well done :+1:

**Pull request merged**
