### PR TITLE
[WINDUPRULE-1037] Improves EAP 8 JSP rule, clarifying it is about Fac…

### PR DESCRIPTION
**Pull request by emmartins**
…es removing support for JSP, and make it potential
Issue: https://issues.redhat.com/browse/WINDUPRULE-1037

### CODE REVIEW

**Comment by PhilipCattanach** [comment]
@emmartins - You need to update the wording in the test, as you've changed the message.
The test is failing with

Error with test: eap8-faces-00009-test
	Cause: (Rule: eap8-faces-00009-test) Assertion failed: [eap8-faces-00009] The hint was not found!

**Comment by emmartins** [comment]
@PhilipCattanach think I need some help here, I changed the test message but it is still failing, maybe something not good with the rule itself? The idea is to catch  whenever one of the 2 dependencies is present AND there is a jsp file...

**Comment by emmartins** [comment]
all seems good to merge, thanks for the help

**Comment by PhilipCattanach** [comment]
Successfully tested, happy to merge. thanks @emmartins

**Comment by PhilipCattanach** [comment]
There is an integration test that is failing beacsue of a broken link. Nothing to do with this change, so we can address that separately under https://issues.redhat.com/browse/WINDUPRULE-1039

**Pull request merged**
