### PR TITLE
WINDUPRULE-411 Camel 3 springboot starters groupId have been renamed

### PR DESCRIPTION
**Pull request by johnpoth**
https://issues.redhat.com/browse/WINDUPRULE-411

Thanks !

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by mrizzi** [comment]
test this please

**Comment by mrizzi** [comment]
This PR depends on https://github.com/windup/windup/pull/1372 to be merged before being able to build successfully.

**Comment by m-brophy** [comment]
retest

**Comment by mrizzi** [comment]
retest

**Pull request merged**
