### PR TITLE
taiga tasks 179_180 - reviewed and added rules for migration path fro…

### PR DESCRIPTION
**Pull request by mareknovotny**
…m EAP5->7

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Build triggered. sha1 is merged.

**Comment by windupgithubbot1** [comment]
Build started sha1 is merged.

**Comment by mareknovotny** [comment]
retest

**Comment by jsight** [comment]
retest

**Comment by jsight** [comment]
retest

**Comment by jsight** [comment]
The maven settings are pointing to a sonatype that doesn't exist, but I'm not sure why that would cause these errors anyway.

**Comment by jsight** [comment]
retest

**Comment by jsight** [comment]
Ah, it looks like JBoss Nexus sometimes serves invalid checksums (maybe a caching issue?). Changing the checksum policy for the repo in artifactory to ignore this seems to be helping.

**Comment by jsight** [comment]
Yay, successful test. :)

**Comment by mareknovotny** [comment]
awesome discovery, I didn't expect checksums are wrong. Thanks Jess-

**Comment by jsight** [comment]
Yeah, I was surprised by it too. I still wonder if the client is pulling the wrong metadata somehow. But I have seen weird caching issues with jboss nexus in the past, too, so its hard to tell.

**Pull request merged**
