### PR TITLE
WINDUP-911 take only *.windup.xml files for built jar artifact

### PR DESCRIPTION
**Pull request by mareknovotny**
https://issues.jboss.org/browse/WINDUP-911

### CODE REVIEW

**Comment by jsight** [comment]
Won't this also exclude XSLT files?

**Comment by mareknovotny** [comment]
yes, it will, haven't thought about them :(, I will add an inclusion for them

**Comment by jsight** [comment]
This is also filtering out API jars that are used for class reachability analysis (when that feature is enabled).

**Comment by mareknovotny** [comment]
@jsight  do you mean the java API? I will add them too then.

**Comment by mareknovotny** [comment]
I got it now, I didn't know they are here in rulesets in jboss-eap/api-jars/*.jars

**Comment by OndraZizka** [comment]
I have tried this using
 --input /home/ondra/work/Migration/TestApps/_apps/jee-example-app-1.0.0-unparsable.ear --output /tmp/Windup/resJee  --overwrite --batchMode --debugx --keepWorkDirs --target eap --enableClassNotFoundAnalysis
and it worked fine.

**Comment by OndraZizka** [comment]
But now I checked and the artifact still has 17 MB.

**Pull request merged**
