### PR TITLE
[WINDUPRULE-759] eapxp_bootable_jar_maven_plugin_configuration_change…

### PR DESCRIPTION
**Pull request by emmartins**
…s ruleset
Issue: https://issues.redhat.com/browse/WINDUPRULE-759

### CODE REVIEW

**Comment by emmartins** [comment]
Please note that the link is pointing to a staged document

**Comment by emmartins** [comment]
@mrizzi could this could be improved with a quick fix that would replace the XML element name?

**Comment by PhilipCattanach** [comment]
@emmartins - (as with the other PR) I have reviewed the code and tested this rules set. Everything looks fine. Thank you!
The link didn't work but I presume this is because the guide hasn't been published yet?
Marco is working on a fix windup/windup#1417 for some Eclipse dependencies issues that should be merged to master shortly and will allow the default tests above to complete. When those things are done I'll merge this to master.

**Comment by emmartins** [comment]
@PhilipCattanach the link should work if you log in to customer portal, it's a staged one. Once published all needed should be to remove the ?lb_target=stage from the URL

**Comment by mrizzi** [comment]
retest

**Comment by emmartins** [comment]
updated to remove the "?lb_target=stage" part of the link (please note the doc is not yet published tho)

**Comment by PhilipCattanach** [comment]
Tested the ruleset and everything looked fine. Verified the documentation link using the staged one -  https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.4/html-single/jboss_eap_xp_upgrade_and_migration_guide/index?lb_target=stage#microprofile-application-migration-bootable-jar_default

**Comment by jonathanvila** [comment]
retest

**Comment by jonathanvila** [comment]
retest

**Pull request merged**
