### PR TITLE
WINDUP-656 - webappext.xmi and webappbnb.xmi

### PR DESCRIPTION
**Pull request by OndraZizka**

### CODE REVIEW

**Comment by lincolnthree** [comment]
Hey Ondra, it looks like this is primarily a reformat with some touchups to messaging. I also see some added test-data files, but no tests or rules that utilize them. I'm not sure how this PR relates to WINDUP-656 without seeing any new rules or tests. It's possible I missed something because the formatting of these files appears to have changed dramatically here, but please let me know what your intent is here. Thanks.

**Comment by lincolnthree** [comment]
Ok, I did find the rules after digging a bit more... could you please re-base this? Thanks.

**Comment by lincolnthree** [comment]
It would be nice if you could send a PR that includes *only* the new functionality you want to add, minus the updates to other pieces of the ruleset.

**Comment by lincolnthree** [comment]
I take back my previous comments. Could you please rebase this so it can be merged? Thanks.

**Comment by OndraZizka** [comment]
Hi, sure, I will rebase. What's wrong on reformatting? I thought you specifically asked me to reformat everything I commit. Did that change?

**Comment by lincolnthree** [comment]
I think my formatting is wrong. Hence I retract my statements :)

**Pull request merged**
