### PR TITLE
WINDUPRULE-626: cloud skipper source analysis condition added

### PR DESCRIPTION
**Pull request by m-brophy**

### CODE REVIEW

**Comment by PhilipCattanach** [comment]
Tested successfully. Thanks @m-brophy

**Comment by PhilipCattanach** [comment]
@m-brophy - Thanks Mark tested successfully. I can see the issue being generated from the POM.xml file as well as the jar

**Comment by m-brophy** [comment]
retest

**Review by mrizzi — APPROVED** [review]
LGTM :+1: 
Thanks @m-brophy

**Pull request merged**
