### PR TITLE
WINDUPRULE-111 and WINDUPRULE-110

### PR DESCRIPTION
**Pull request by mbriskar**

### CODE REVIEW

**Comment by Ladicek** [comment]
Change the `eap6-xml-02000` rule in `eap6-xml.windup.xml` too? Please? :-)

**Comment by mbriskar** [comment]
sure :)

**Comment by Ladicek** [comment]
It still says that "There is no workaround currently." The message in the new rule "JBoss Web was replaced by Undertow, which does not contain support for the Valve functionality. It may be needed to migrate to Undertow handlers" is better.

**Comment by mbriskar** [comment]
Done. What about the documentation?

**Comment by Ladicek** [comment]
What kind of documentation do you think of?

**Comment by mbriskar** [comment]
About how to migrate to undertow handlers from valves

**Comment by Ladicek** [comment]
Right. We have something in EAP 7 Migration Guide, if you want to see that, ping me on IRC :-)

**Comment by Ladicek** [comment]
LGTM. The documentation links point to a section of documentation that speaks about subsystem migration, but the part of the documentation that speaks about application migration is plain wrong, so this will be better for now.

**Comment by Ladicek** [comment]
Thanks for the other commit. Looks good to me.

In the meantime, I fixed https://docs.jboss.org/author/display/WFLY10/How+do+I+migrate+my+application+from+AS7+to+WildFly#HowdoImigratemyapplicationfromAS7toWildFly-JBossWebValves so that it now contains some actually useful info. Can we link to that instead, in the rules for valves?

**Comment by mbriskar** [comment]
Ok I have referenced that link. The only thing that I am not that much satisfied with is xpath "//valve". This will be slow and will run on every xml file that will be registered

**Comment by Ladicek** [comment]
It's enough to look for `<valve>` only in `jboss-web.xml`.

**Comment by mbriskar** [comment]
oh good point

**Comment by Ladicek** [comment]
One other thing -- AFAIK, you don't really have to look for `//valve`, it's enough to look for `/jboss-web/valve`.

**Comment by mareknovotny** [comment]
@mbriskar have you seen previous comment about 

> it's enough to look for `/jboss-web/valve`.
?

**Comment by mbriskar** [comment]
I have changed the //valve to jboss-web/valve

**Pull request merged**
