### PR TITLE
WINDUPRULE-512 camel-maven-plugin has been split

### PR DESCRIPTION
**Pull request by johnpoth**
https://issues.redhat.com/browse/WINDUPRULE-512

to run tests: `mvn -DrunTestsMatching=xml-removed-components clean test -nsu`

Thanks !

### CODE REVIEW

**Comment by mmelko** [comment]
retest

**Comment by jonathanvila** [comment]
retest

**Comment by jonathanvila** [comment]
@mmelko could you please check the tests ?

**Comment by m-brophy** [comment]
retest

**Comment by johnpoth** [comment]
@jonathanvila rebased, thanks for reviewing!

**Comment by jonathanvila** [comment]
LGTM :+1:

**Comment by johnpoth** [comment]
Thanks @jonathanvila !

**Pull request merged**
