### PR TITLE
Updated rulesets to use category id

### PR DESCRIPTION
**Pull request by jsight**
Needs: https://github.com/windup/windup/pull/1035

### CODE REVIEW

**Comment by mareknovotny** [comment]
I have uploaded xsd schema with version string as http://windup.jboss.org/schema/jboss-ruleset/windup-jboss-ruleset-3.0.xsd, all others are there too. Stable version 2.7.0.Final schema is a symlink http://windup.jboss.org/schema/jboss-ruleset/windup-jboss-ruleset-2.7.xsd to one level up as http://windup.jboss.org/schema/windup-jboss-ruleset.xsd

**Comment by mareknovotny** [comment]
retest

**Comment by jsight** [comment]
Ok, thanks @mareknovotny

**Comment by mareknovotny** [comment]
just waiting on tests finishing before merging

**Pull request merged**
