### PR TITLE
Added support for dotnet cloud-readiness analysis

### PR DESCRIPTION
**Pull request by vinodpahuja**

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by vinodpahuja** [comment]
@windupgithubbot1 any further input on this ?

**Comment by mrizzi** [comment]
test this please

**Comment by PhilipCattanach** [comment]
@vinodpahuja - Thank you very much for submitting this Pull Request. 
We are always very grateful for contributions to the  Windup project.

We have some standards that all PRs must adhere to before they can be considered for merging into the master branch.
Specifically we require that each windup.xml ruleset has a corresponding windup.test.xml test.
Essentially we write rules to test the rules.
Please see this example PR https://github.com/windup/windup-rulesets/pull/770/files
You will notice in the eap8.ejb.windup.test.xml there is a rulePath tag that identifies the path to the corresponding ruleset, and a testDataPath that defines the data folder that the ruleset will be executed against. We like to have granular tests data folders, so there is a folder dedicated to each ruleset. In this example the test data is in the data/ejb subfolder.
Also worth noting in the tests is the iterable-filter tag that shows number of times the rule is expected to fire.
And the hint-exists contains the message (not the title) that is expected to be generated when the rule fires. 
To test an individual ruleset you can simply run the command from you local windup-rulesets folder
mvn -DrunTestsMatching=RuleTestFileName  clean test
So a concrete example would be
mvn -DrunTestsMatching=eap8.ejb  clean test

Please update your PR to add the tests and granular tests/data/ subfolders.
What also adds value to the rules are link tags to public facing urls that contain relevant supporting information. 

More information about rules development can be found in the [Rule Development Guide](https://access.redhat.com/documentation/en-us/migration_toolkit_for_runtimes/1.0/html/rules_development_guide/reference_material#how_story_points_are_estimated_in_rules)
Please pay special attention to the Story Points and Task Category references sections of the guide (A.1.2 and A.1.3)

**Comment by vinodpahuja** [comment]
Closing the PR as repo is outdated. Will raise fresh PR.

**Pull request closed without merging**
