### PR TITLE
add more azure rules

### PR DESCRIPTION
**Pull request by KaiqianYang**

### CODE REVIEW

**Comment by PhilipCattanach** [comment]
Hi @KaiqianYang 
Thank you for submitting this PR.
I will get it reviewed today. 
Much appreciated.
Phil

**Comment by PhilipCattanach** [comment]
Hi @KaiqianYang 
There doesn't appear to be a windup.test.xml file, or data, for the  new azure-os-specific.windup.xml ruleset
Can you add them to the PR please?
Thank you,
Phil

**Comment by KaiqianYang** [comment]
> Hi @KaiqianYang Thank you for submitting this PR. I will get it reviewed today. Much appreciated. Phil

@PhilipCattanach Thanks!
And I created a issue found in my testing, thinking it needs attention https://issues.redhat.com/browse/WINDUP-3837

**Comment by KaiqianYang** [comment]
> Hi @KaiqianYang There doesn't appear to be a windup.test.xml file, or data, for the new azure-os-specific.windup.xml ruleset Can you add them to the PR please? Thank you, Phil

@PhilipCattanach  Yeah sure, I will add it. And I also created a issue related to this rule, it's a question about <OverrideRules> https://issues.redhat.com/browse/WINDUP-3814  Looking forward to reply.

**Comment by PhilipCattanach** [comment]
Thanks @KaiqianYang - I'll have a look at https://issues.redhat.com/browse/WINDUP-3814  too and respond in that Jira's comments

**Comment by KaiqianYang** [comment]
> https://issues.redhat.com/browse/WINDUP-3837



> Thanks @KaiqianYang - I'll have a look at https://issues.redhat.com/browse/WINDUP-3814 too and respond in that Jira's comments

Thanks @PhilipCattanach. And the issue https://issues.redhat.com/browse/WINDUP-3837 may also cause unit test failure

**Pull request merged**
