### PR TITLE
WINDUPRULE-412 Some classes in the org.apache.camel.impl pack…

### PR DESCRIPTION
**Pull request by johnpoth**
…age were moved to org.apache.camel.support

https://issues.redhat.com/browse/WINDUPRULE-412

Thanks !

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by mrizzi** [comment]
test this please

**Comment by mrizzi** [comment]
retest

**Comment by johnpoth** [comment]
@mrizzi done! I've added some test classes. Hope it's ok

**Comment by mrizzi** [comment]
add to whitelist

**Pull request merged**
