### PR TITLE
Winduprule 501

### PR DESCRIPTION
**Pull request by johnpoth**
https://issues.redhat.com/browse/WINDUPRULE-501

To run tests: `mvn -DrunTestsMatching=java-generic-information clean test -nsu`

Thanks !

### CODE REVIEW

**Comment by johnpoth** [comment]
retest

**Comment by johnpoth** [comment]
@jonathanvila, updated thanks!

**Comment by jonathanvila** [comment]
You have 4 rules with the same condition : 
<javaclass references="org.apache.camel.CamelContext.{method}({*})" >
Why ? I assume this will create an overhead and waste innecessary analysis time.

**Comment by johnpoth** [comment]
Hi @jonathanvila, thanks for reviewing!

The four rules check the same class but different methods. This is because they were moved to different locations for different reasons. The hint message is also different

**Comment by jonathanvila** [comment]
> Hi @jonathanvila, thanks for reviewing!
> 
> The four rules check the same class but different methods. This is because they were moved to different locations for different reasons. The hint message is also different

buffff, sorry for this.... You are totally right about this.

**Comment by jonathanvila** [comment]
LGTM :+1:

**Comment by jonathanvila** [comment]
@johnpoth could you please rebase *master* ? apparently when rebasing it tests fail.

**Comment by johnpoth** [comment]
@jonathanvila looks like it is up to date ? 

Running `mvn -DrunTestsMatching=java-generic-information clean test` locally seems ok. I'm probably missing something...

**Comment by jonathanvila** [comment]
> @jonathanvila looks like it is up to date ?
> 
> Running `mvn -DrunTestsMatching=java-generic-information clean test` locally seems ok. I'm probably missing something...

apparently it was something with my local env ..... I always checkout your PR branches, and pull upstream master to check everything will be fine once merged. Sometimes if the PR branch is  behind master could happen that the tests run ok but once master is merged something is broken.

**Pull request merged**
