### PR TITLE
Winduprule 715

### PR DESCRIPTION
**Pull request by PhilipCattanach**
Correction to the message. The original PR mistakenly had the text for Starting the Application rather than the Fast-jar as default.

### CODE REVIEW

**Comment by PhilipCattanach** [comment]
@m-brophy Humble apologies for asking you to look at this rule again Mark. I've just this morning noticed an issue with the message.

**Comment by m-brophy** [comment]
retest

**Comment by m-brophy** [comment]
I think yoiu've added the test file for the run-jar to this PR by mistake

**Comment by PhilipCattanach** [comment]
@m-brophy - Good spot  - I've deleted that extra test file - thanks

**Review by m-brophy — APPROVED** [review]

**Pull request merged**
