### PR TITLE
Formatted few rules (wrong indentation).

### PR DESCRIPTION
**Pull request by OndraZizka**
Changed few messages.

### CODE REVIEW

**Comment by jsight** [comment]
The tests do not pass and in some of the cases, markdown formatting was changed in ways that make the resulting output less clear to look at (for example, the PostgreSQL JDBC URL rule removed some useful indentation).

**Comment by OndraZizka** [comment]
Does Markdown work if there are spaces before the whole ``` code block?

**Comment by OndraZizka** [comment]
Does Markdown work if there are spaces before the whole ``` code block?

**Comment by jsight** [comment]
Our xml loader deals with that as it is common for the entire text block to be indented in the xml.

**Comment by d-s** [comment]
Let's wait to merge this until after we tag 2.6.0.Final since we don't have very thorough QA right now. (I'm afraid of a big formatting fix like this introducing some issue we don't catch if it's thrown in at the last minute.)

**Comment by windupgithubbot1** [comment]
Build triggered. sha1 is original commit.

**Comment by mareknovotny** [comment]
this needs a rebase if it is still considered for merging.

**Pull request closed without merging**
