### PR TITLE
https://issues.jboss.org/browse/WINDUP-710 - adding XSD for ruletest …

### PR DESCRIPTION
**Pull request by mareknovotny**
…and updated *.windup.test.xml files to it and added validation to schema in the build.

### CODE REVIEW

**Comment by mareknovotny** [comment]
This PR is like a preview how it should work, we can change XSD definition(s) on request as I grabbed mostly what is in existing *.windup.test.xml files so far.

**Comment by mareknovotny** [comment]
I rebased the PR commit not to conflict with master branch

**Comment by mareknovotny** [comment]
rebased and updated to current status quo

**Comment by jsight** [comment]
This does not build as the ruleset namespace is not the same as the test namespace. So none of the test rulesets parse correctly.

**Comment by mareknovotny** [comment]
Do you mean by different namespace this https://github.com/mareknovotny/windup-rulesets/commit/f5e043ef5eb61034f782294aeeaa639827dc167a#diff-38c76d42b2361873851466c4de3a300dR45 ?

I will rebase to current status and update new rules to have ruletest XSD too.

**Comment by jsight** [comment]
When I ran the tests, they failed on every test due to a NPE as they didn't
load any rules.

**Comment by mareknovotny** [comment]
interesting ... I rebased the branch and i got the validation errors, but that is due some wrong merges, as I can't see there correct namespace in declaration. I will go through them and do update to correct one.

**Comment by mareknovotny** [comment]
I got what you meant, different namespace in element handlers breaks the loading of test rules. I haven't considered the reusing them in xsd breaks testing rules. I will think about it.

**Comment by mareknovotny** [comment]
I am closing this as I will update rather https://github.com/windup/windup/blob/master/config-xml/schema/windup-jboss-ruleset.xsd to have missing windup test elements and will create new PR for updating existing windup rulesets with it.

**Pull request closed without merging**
