### PR TITLE
WINDUPRULE- 502,505,506,507,497

### PR DESCRIPTION
**Pull request by mmelko**
https://issues.redhat.com/browse/WINDUPRULE-502
https://issues.redhat.com/browse/WINDUPRULE-505
https://issues.redhat.com/browse/WINDUPRULE-506
https://issues.redhat.com/browse/WINDUPRULE-507
https://issues.redhat.com/browse/WINDUPRULE-497

### CODE REVIEW

**Comment by mmelko** [comment]
depends on: https://github.com/windup/windup-rulesets/pull/442

**Comment by mmelko** [comment]
retest

**Comment by mmelko** [comment]
retest

**Comment by mmelko** [comment]
retest

**Comment by jonathanvila** [comment]
retest

**Comment by jonathanvila** [comment]
LGTM :+1:

**Pull request merged**
