### PR TITLE
modify connect usage rules for azure, add kafka discovery

### PR DESCRIPTION
**Pull request by KaiqianYang**
1)links in connect usage hints point to JBoss doc, override them in azure rules. 2)add kafka

### CODE REVIEW

**Comment by PhilipCattanach** [comment]
Linked to Jira https://issues.redhat.com/browse/WINDUPRULE-993

**Comment by PhilipCattanach** [comment]
@KaiqianYang - Sorry for the delay in reviewing this PR.

I do not understand why the connect.xml rules have been copied from the technology-usage folder to the azure folder.
Those rule sets in the technology-usage folder are not linked to a specific target, so they will always be selected for execution.
   
In the connect-technology-usage ruleset the "Kafka Client" technology-tag should be allocated to "Streaming" rather than "Other" technology sub-category.

**Comment by KaiqianYang** [comment]
> Streaming

@PhilipCattanach Thanks for your review!

Yes, exactly, I understand that technology-usage rulesets apply to all targets. While in the rulesets, the links in hints are on Red Hat JBOSS, e.g., [connect-technology-usage](https://github.com/windup/windup-rulesets/blob/master/rules/rules-reviewed/technology-usage/connect.windup.xml#L33C31). For execution targeting Azure, there is no need to show docs of JBOSS EAP, right? So, I override this ruleset in the azure folder, removing the doc links, so that the JBOSS docs won't bring about confusion.

For the tag of Kafka, I have updated it to the "Streaming" as you suggested.

Thanks!

**Comment by KaiqianYang** [comment]
> @KaiqianYang - Sorry for the delay in reviewing this PR.
> 
> I do not understand why the connect.xml rules have been copied from the technology-usage folder to the azure folder. Those rule sets in the technology-usage folder are not linked to a specific target, so they will always be selected for execution.
> 
> In the connect-technology-usage ruleset the "Kafka Client" technology-tag should be allocated to "Streaming" rather than "Other" technology sub-category.

@PhilipCattanach Thanks for your review!

Yes, exactly, I understand that technology-usage rulesets apply to all targets. While in the rulesets, the links in hints are on Red Hat JBOSS, e.g., [connect-technology-usage](https://github.com/windup/windup-rulesets/blob/master/rules/rules-reviewed/technology-usage/connect.windup.xml#L33C31). For execution targeting Azure, there is no need to show docs of JBOSS EAP, right? So, I override this ruleset in the azure folder, removing the doc links, so that the JBOSS docs won't bring about confusion.

For the tag of Kafka, I have updated it to the "Streaming" as you suggested.

Thanks!

**Comment by PhilipCattanach** [comment]
Hi @KaiqianYang 
I had a chat with @mrizzi how we could improve these technology discovery rules and only display the EAP supported configurations ink if the analysis target is eap.
Marco refactored the rules to do that under PRs https://github.com/windup/windup-rulesets/pull/962 (for the connect rules) and under PR https://github.com/windup/windup-rulesets/pull/963 for the database rules.
The former PR also contains the Kafka Client technology identification and classification. Both PRs have been merged to master so this PR is no longer required. Thanks for the contribution, our rulesets are definitely better as a consequence of the work the 3 of us have done.

**Comment by KaiqianYang** [comment]
> Hi @KaiqianYang I had a chat with @mrizzi how we could improve these technology discovery rules and only display the EAP supported configurations ink if the analysis target is eap. Marco refactored the rules to do that under PRs #962 (for the connect rules) and under PR #963 for the database rules. The former PR also contains the Kafka Client technology identification and classification. Both PRs have been merged to master so this PR is no longer required. Thanks for the contribution, our rulesets are definitely better as a consequence of the work the 3 of us have done.

Great! Thanks, @PhilipCattanach @mrizzi . 

I appreciate the improvements you both made to the technology discovery rules. Thank you for your dedication and collaboration. I'm glad that our combined efforts have had a positive impact on the rulesets.

**Pull request closed without merging**
