### PR TITLE
[WINDUPRULE-1015] Rules for APIs deprecated for removal

### PR DESCRIPTION
**Pull request by jmle**
See [Jira ticket](https://issues.redhat.com/browse/WINDUPRULE-1015).

### CODE REVIEW

**Comment by PhilipCattanach** [comment]
@jmle - I looked at the rules and there seems nothing to cover the following packages in the JDK18 sub-set
java.awt.*, java.lang.*, java.util.*, and javax.imageio.*

**Comment by jmle** [comment]
> @jmle - I looked at the rules and there seems nothing to cover the following packages in the JDK18 sub-set java.awt._, java.lang._, java.util._, and javax.imageio._

Hi @PhilipCattanach, those methods are covered by this [previously merged PR](https://github.com/windup/windup-rulesets/pull/1009).

**Comment by PhilipCattanach** [comment]
Thanks @jmle - Are we missing java.lang.Thread.stop ?
I can see all of the finalize and runFinalization methods are covered

**Comment by PhilipCattanach** [comment]
@jmle 
I'm getting an error 
 WindupRulesTest.testWindupRules:155 
	Error with test: deprecation-test-00005
	Cause: (Rule: deprecation-test-00005) Assertion failed: deprecation-test-00005 - the hint was not found

However the rule has fired, once as expected and the message in the test looks right. I don't know why it is failing for me. Is it running locally OK for you?

**Comment by jmle** [comment]
> @jmle I'm getting an error WindupRulesTest.testWindupRules:155 Error with test: deprecation-test-00005 Cause: (Rule: deprecation-test-00005) Assertion failed: deprecation-test-00005 - the hint was not found
> 
> However the rule has fired, once as expected and the message in the test looks right. I don't know why it is failing for me. Is it running locally OK for you?

@PhilipCattanach my bad, I was missing some escape dashes

**Comment by PhilipCattanach** [comment]
@jmle The tests ran successfully.
I think the source technology tags **in each** of the rulesets needs to be updated 
For example in deprecation-openjdk18.windup.xml  
sourceTechnology id="openjdk" versionRange="(,18)"

which means <= 18
shouldn't that be <=17

**Comment by PhilipCattanach** [comment]
D-oh! my mistake!
the version range is correct I was misreading it as (,18]
We are all good I can merge the PR

**Pull request merged**
