### PR TITLE
Escaping few { characters

### PR DESCRIPTION
**Pull request by mbriskar**

### CODE REVIEW

**Comment by lincolnthree** [comment]
Hey Matej,

Could you please rebase this onto the latest?

Thanks!

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-rulesets-master/2/
Test FAILed.

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-rulesets-master/4/
Test FAILed.

**Comment by jsight** [comment]
retest

**Comment by windupgithubbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://10.3.8.5//job/windup-rulesets-master/5/
Test PASSed.

**Pull request merged**
