### PR TITLE
Winduprule 142 Spring XML Technology Report and Remote Services

### PR DESCRIPTION
**Pull request by jonathanvila**
depends on https://github.com/windup/windup/pull/1335

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by mrizzi** [comment]
@windupgithubbot1 Test this please

**Comment by jonathanvila** [comment]
retest

**Comment by mrizzi** [comment]
@windupgithubbot1 add to whitelist

**Comment by m-brophy** [comment]
retest

**Comment by m-brophy** [comment]
I'm happy with these changes, and tested successfully in conjunction with the associated changes to windup/windup. There's a failing build here however. So longs as we can get it to build successfully I'm happy for this to be merged into master.

**Comment by m-brophy** [comment]
retest

**Pull request closed without merging**
