### PR TITLE
WINDUPRULE-731: quarkus1-13 jackson upgrade rule

### PR DESCRIPTION
**Pull request by m-brophy**
https://issues.redhat.com/browse/WINDUPRULE-731

### CODE REVIEW

**Comment by PhilipCattanach** [comment]
@m-brophy the rules executed successfully. The message needs to have the string application.properties highlighted as per the guide.

**Comment by PhilipCattanach** [comment]
@m-brophy - quarkus1-13-jackson-jar.windup.test.xml fail message is wrongly referring to quarkus1-13-jackson-00000

**Comment by m-brophy** [comment]
Those 2 issues should be fixed now

**Comment by PhilipCattanach** [comment]
I can confirm the issues have been fixed. I will merge to master as soon as the automated tests  are complete.

**Pull request merged**
